### ISSUE TITLE
Setup buildignore + conda + notebooks

### ISSUE THREAD

**Issue by shamindras** [shamindras/ascifit#1]
## Task list 

- [x] Add `.rbuildignore` include jupyter notebooks.
- [x] Add `conda` envs.
- [x] Add the jupyter notebooks.
- [x] Update readme.Rmd.
- [x] Update citation.
- [x] Build the `Readme.Rmd`.
